adopted-ember-addons/ember-cp-validations

CHANGELOG.md

Changelog.

---

README.md

Show lib use without Ember Data.

---

addon/utils/validation-result-collection.js
addon/utils/validation-result.js
blueprints/ember-cp-validations/index.js
bower.json
package.json
tests/acceptance/dummy-index-test.js
tests/dummy/app/templates/components/validated-input.hbs
tests/dummy/app/templates/index.hbs
tests/unit/build-validation-test.js

* Some simple integration tests for dummy app
* Some forgotten test cases for 1.0.2 bugfix release
* Forgotten link to messages in validation-result object
* upgrade ember-load-initializer
* upgrade ember-moment

test cases, some small fixes

---

addon/utils/flatten.js
addon/utils/validation-result-collection.js
addon/utils/validations-factory.js
blueprints/ember-cp-validations/index.js
package.json
tests/unit/utils/flatten-test.js

Remove lodash requirement.
Addresses #30.

Remove lodash requirement.

---

blueprints/validator-test/index.js
blueprints/validator-test/mocha-files/tests/unit/validators/__name__-test.js
blueprints/validator-test/qunit-files/tests/unit/validators/__name__-test.js
blueprints/validator/files/app/validators/__name__.js
package.json

Support Ember-CLI-Mocha users.

---

addon/validators/base.js
addon/validators/messages.js
app/validators/confirmation.js
app/validators/date.js
app/validators/length.js
app/validators/messages.js
docs/docs/messages.md
docs/docs/style.css
docs/docs/validating.md
docs/docs/validators/common.md
docs/docs/validators/messages.md
docs/mkdocs.yml
package.json
tests/unit/validations/factory-dependent-keys-test.js
tests/unit/validations/model-relationships-test.js
tests/unit/validators/length-test.js
tests/unit/validators/messages-test.js

* Create extendable hook for ember-i18n solutions
* Removed String.fmt dependency
* Better ability to extend message strings and add new ones
* Updated docs and added tests
Should resolve #9, #33

support for i18n solutions

---

addon/validations/factory.js
addon/validators/base.js
app/validators/collection.js
app/validators/confirmation.js
app/validators/date.js
app/validators/dependent.js
app/validators/exclusion.js
app/validators/format.js
app/validators/inclusion.js
app/validators/length.js
app/validators/presence.js
blueprints/ember-cp-validations/index.js
bower.json
package.json
tests/dummy/app/models/user-detail.js
tests/unit/validations/factory-general-test.js
tests/unit/validators/base-test.js
tests/unit/validators/collection-test.js
tests/unit/validators/confirmation-test.js
tests/unit/validators/date-test.js
tests/unit/validators/dependent-test.js
tests/unit/validators/exclusion-test.js
tests/unit/validators/format-test.js
tests/unit/validators/inclusion-test.js
tests/unit/validators/length-test.js
tests/unit/validators/presence-test.js

* Add buildOptions and processOptions hooks
* Default options for validators (#38)
* All options can be functions that are called right before validate
via processOptions
* Removed moment dependency (#30)

Add hooks in base validator, remove moment dependency, default options

---

app/validators/presence.js
tests/unit/validations/model-relationships-test.js

Handle ember-data promise proxy based instances in presence

---

README.md

Updated to the Code to use ES6 `const` instead of `var`

Update the readme code

---

bower.json
config/release.js
package.json
tests/dummy/app/index.html

Use ember-cli-release and some random fixes

Use ember-cli-release to automate dummy app deploy

---

README.md

Just to align with the previous example.

add return from model hook in readme example

---

app/validators/date.js
tests/dummy/app/app.js
tests/helpers/resolver.js

Howdy partner, I fixed those moment issues and also, just for fun .. fixed up usage of resolver and load-initializer to resolve warnings ..

fixed moment date parsing deprecations

---

addon/index.js
addon/utils/assign.js
addon/utils/cycle-breaker.js
addon/utils/flatten.js
addon/utils/meta-data.js
addon/validations/error.js
addon/validations/factory.js
addon/validations/result-collection.js
addon/validations/result.js
addon/validations/validator.js
addon/validators/base.js
addon/validators/messages.js
app/validators/belongs-to.js
app/validators/collection.js
app/validators/confirmation.js
app/validators/date.js
app/validators/dependent.js
app/validators/ds-error.js
app/validators/exclusion.js
app/validators/format.js
app/validators/has-many.js
app/validators/inclusion.js
app/validators/number.js
app/validators/presence.js

Much needed code cleanup with proper ES6 syntax using eslint rules

Code cleanup

---

addon/validators/belongs-to.js
addon/validators/has-many.js
tests/dummy/app/styles/app.css
tests/integration/validations/model-relationships-test.js

Add null safe checks for relational validators after promise resolves

---

addon/validators/date.js

Fix some date formatting issues

---

blueprints/validator-test/index.js

Fix blueprint warning.

---

addon/utils/utils.js
addon/validations/internal-result-object.js
addon/validators/date.js
addon/validators/ds-error.js

Resolves #250.
@basz @alexparker can you checkout this branch and see if that fixes your problem? Im not able to recreate the issue from my end but I think this should do it.

[BUGFIX] Fix require module

---

blueprints/validator-test/index.js

Fix ember-cli deprecation warning

---

addon/validations/factory.js

Resolves #306.
**Before**
**After**

[FEATURE] Place mixin under a named scope for Ember Inspector

---

bower.json
package.json
tests/dummy/app/components/validated-input.js
tests/dummy/app/controllers/index.js
tests/dummy/app/routes/index.js
tests/dummy/app/styles/form.less
tests/dummy/app/templates/index.hbs

Resolves #328.
- Update validate-input component to use focuOut instead of isDirty
- General update of demo app

Updated demo + validated-input component

---

addon/utils/utils.js

[BUGFIX] Add a check if ember-data exists for isDSManyArray

---

addon/index.js
addon/utils/should-call-super.js
addon/validations/factory.js
addon/validations/validator.js
addon/validators/base.js
addon/validators/belongs-to.js
addon/validators/confirmation.js
addon/validators/messages.js
tests/dummy/app/templates/index.hbs

Great addon! I made a few small typo-fixes as I was reading through the documentation, hope you don't mind :-)

Made some spelling corrections in the documentation

---

tests/dummy/app/components/validated-input.js
tests/dummy/app/templates/index.hbs

Resolves #355.
- Remove targetObject usage in dummy app

[BUGFIX] Remove targetObject usage in dummy app

---

addon/utils/utils.js
addon/validations/factory.js
addon/validations/validator.js
addon/validators/base.js
tests/integration/validations/factory-general-test.js

- Add volatile option
- Code cleanup for validateAttribute
Tasks:

[FEATURE] Volatile option

---

.travis.yml
addon/validations/factory.js
addon/validators/base.js
bower.json
config/ember-try.js
package.json
tests/dummy/config/environment.js
tests/helpers/setup-object.js
tests/helpers/start-app.js
tests/index.html
tests/integration/validations/factory-general-test.js

Ember 2.10 Upgrade

---

README.md

Hey Offir, now that you and Ryan have finished the video let's link to it in the readme!

Show poster and link to EmberMap video

---

tests/dummy/app/styles/form.less

Fix typo in dummy form prefixed selector

---

blueprints/validator-test/index.js
blueprints/validator-test/mocha-0.12-files/tests/unit/validators/__name__-test.js

Updated blueprints to account for new mocha syntax

---

addon/validations/factory.js

Resolves #502.
- Move attrs teardown logic to `willDestroy`

[BUGFIX] Ember Data 2.13 Nested Key Destroy

---

package.json
yarn.lock

bumped version on ember-string-ishtmlsafe-polyfill dependency.

---

.bowerrc
.travis.yml
bower.json
package.json
yarn.lock

these deps are imported via npm

remove bower usage

---

addon/index.js

Resolves # .
- Update documentation regarding depedentKeys nomenclature
Tasks:

Update documentation regarding dependentKeys

---

package.json
yarn.lock

to take advantage of https://github.com/offirgolan/ember-validators/pull/57 :)

Update `ember-validators` to v1.0.4

---

testem.js

This PR should hopefully fix the currently broken CI runs.
/cc @offirgolan

testem: Use `--no-sandbox` flag on TravisCI (v3.x)

---

package.json
yarn.lock

chore: Bump ember-validators

---

index.js
yarn.lock

Resolves #628
This will allow `ember-cli-htmlbars-inline-precompile` to parallelize itself, which will enable better build performance
/cc @offirgolan

Enable parallel Babel builds

---

index.js

Cherry pick of #629 into the 4.x series.

fix: Enable parallel babel builds

---

CHANGELOG.md
README.md
addon/index.js
addon/validators/base.js
addon/validators/messages.js
package.json
tests/dummy/app/templates/application.hbs
tests/integration/validations/factory-general-test.js
yuidoc.json

I did a search for `/offirgolan` and replaced it with `/adopted-ember-addons`.

Update repository name

---

RELEASE.md
package.json
yarn.lock

Run yarn create rwjblue-release-it-setup

---

.github/workflows/plan-release.yml
.github/workflows/publish.yml
RELEASE.md
package.json
pnpm-lock.yaml

This is part of the upcoming programme guidelines change: https://github.com/adopted-ember-addons/program-guidelines/issues/28

start using release-plan

---

htmlbars-plugins/v-get.js

Fix deprecation with path.original
