docs/validators/format/index.html
Missing comma after allowBlank
=> missing comma in example on validators/format/index

README.md, docs/docs/index.md, htmlbars-plugins/v-get.js, tests/integration/helpers/v-get-test.js
=> Support v-get inside element note attribute strings

addon/validations/error.js, addon/validations/factory.js, addon/validations/result-collection.js, addon/validations/result.js, docs/docs/validating.md, tests/unit/validations/factory-general-test.js
Currently, `validations.messages` exposes a flattened array of all error messages present. It would be useful (for a variety of reasons) to have access to both the message as well as the attribute name it corresponds to.
This PR adds `validations.errors` following the same pattern as `validations.messages` (it also adds `validations.error`).
(docs included)
=> Add enumerable list of all error objects

addon/validations/result-collection.js, addon/validations/result.js
This was pointed out by @davewasmer that result and result-collection
is not uniform. Doing this small change removes some unnecessary code.
=> Uniform result and result-collection

addon/validations/result.js, tests/dummy/app/models/signup.js, tests/unit/validations/ds-model-test.js
For boolean attributes with defaultValue === false, isDirty always returned true. This should fix that. All tests pass.
=> Makes isDirty work properly for boolean

addon/validations/factory.js, addon/validations/result-collection.js, addon/validations/result.js, addon/validations/validator.js, tests/integration/validations/factory-general-test.js
Should resolve #93 
All built options of the validators associated with the results in this collection grouped by validator type
```javascript
// Given the following validators
{
username: [
validator('presence', true),
validator('length', { max: 15 }),
validator('format', { regex: /foo/ }),
validator('format', { regex: /bar/ }),
]
}
```
```js
get(user, 'validations.attrs.username.options')
```
The above will return the following
```js
{
'presence': { presence: true},
'length': { max: 15 },
'regex': [{ regex: /foo/ }, { regex: /bar/ }]
}
```
This will also allow you to do the following: 
```hbs
{{input value=model.username
required=model.validations.attrs.username.options.presence
maxlength=model.validations.attrs.username.options.length.max}}
```
=> validation result options hash

addon/validations/factory.js
=> Debounce should not use an anonymous function

addon/index.js, addon/validations/factory.js, addon/validations/validator.js, package.json, tests/integration/validations/factory-dependent-keys-test.js, tests/integration/validations/factory-general-test.js
Resolves #104 
- Exposes `disabled` option for validators
- Add functionality to define `dependentKeys` in default options (should have already been there)
This will allow to do the following
```js
// Via default options
const Validations = buildValidations({
username: {
debounce: 500,
disabled() { return !this.get('model._enableValidations'); },
dependentKeys: ['_enableValidations'],
validators: [
validator('presence', true),
validator('length', {
max: 15
})
]
}
});
// Via single validator
const Validations = buildValidations({
username: validator('presence', {
presence: true,
disabled() { return !this.get('model._enableValidations'); },
dependentKeys: ['_enableValidations']
})
});
export default DS.Model.extend(Validations, {
'username': attr('string'),
_enableValidations: true
});
``` …
=> Expose disabled validator option

blueprints/validator-test/index.js
This PR is fixing what appears to by a copy-paste/refactoring mistake in the test blueprint fallback code
=> blueprints/validator-test: Fix typo in _filesPath() method

README.md, addon/index.js, addon/utils/assign.js, addon/utils/flatten.js, addon/validations/factory.js, tests/integration/validations/factory-general-test.js, tests/unit/utils/assign-test.js
Resolves #131 
```js
import Ember from 'ember';
import { validator, buildValidations } from 'ember-cp-validations';
const Validations = buildValidations({
'user.firstName': validator('presence', true),
'user.lasName': validator('presence', true),
'account.number': validator('presence', true),
});
export default Ember.Component.extend(Validations, {
user:  { firstName: 'bob', lastName: 'billy' } ,
account: { number: 123, balance: 456 }
isFormValid: Ember.computed.alias('validations.isValid'),
});
```
=> Add support for nested keys in validation rules

.codeclimate.yml, .travis.yml, addon/index.js, addon/validations/factory.js, addon/validators/base.js, app/validators/collection.js, app/validators/format.js, app/validators/presence.js, package.json, tests/dummy/app/app.js, tests/dummy/app/models/user-detail.js, tests/dummy/app/models/user.js, tests/dummy/app/resolver.js, tests/helpers/setup-object.js, tests/integration/validations/factory-dependent-keys-test.js, tests/integration/validations/factory-general-test.js
If you have  specific options you want to propagate throught all your validation rules, you can do so by passing in a global options object.
This is ideal for when you have a dependent key that each validator requires such as the current locale from your i18n implementation, or
you want easily toggle your validations on/off.
```javascript
const Validations = buildValidations(validationRules, globalOptions);
```
```javascript
import Ember from 'ember';
import { validator, buildValidations } from 'ember-cp-validations';
const Validations = buildValidations({
firstName: {
description: 'First Name'
validators: [
validator('presence', {
presence: true,
dependentKeys: ['foo', 'bar']
})
]
},
lastName: validator('presence', true)
}, {
description: 'This field'
dependentKeys: ['i18n.locale', …
```
=> Global options support

addon/validations/factory.js, addon/validators/base.js, tests/helpers/start-app.js
Hi, this is a fix for the deprecation of Ember.merge:
DEPRECATION: Usage of Ember.merge is deprecated, use Ember.assign instead. [deprecation id: ember-metal.merge]
More info: https://github.com/emberjs/ember.js/pull/12303
=> Fix deprecation warning Ember.merge > Ember.assign for ember@2.5.0 

addon/utils/should-call-super.js, addon/utils/utils.js, addon/validations/factory.js, tests/integration/validations/factory-general-test.js, tests/unit/utils/should-call-super-test.js
All credit goes to @rwjblue for thinking this up. (Savage)
Resolves #149
=> Only call super on validations class if it exists via shouldCallSuper

addon/validators/presence.js, tests/unit/validators/presence-test.js
This allows using a validator for a case when value should not consist only of space(s).
=> Introduce `ignoreWhitespace` in presence validator

addon/validations/factory.js, addon/validators/alias.js, addon/validators/base.js, addon/validators/belongs-to.js, addon/validators/collection.js, addon/validators/confirmation.js, addon/validators/dependent.js, addon/validators/ds-error.js, addon/validators/has-many.js, blueprints/validator/files/app/validators/__name__.js, tests/unit/validations/ds-model-test.js, tests/unit/validators/date-test.js
This is a feature that has been a long time coming and requested by many power users. This allows a user to declare custom dependent keys on the validator level for custom validators. This will remove a lot of duplicate code and will also reduce the validation rules pojo. 
Since we only create the `ValidationsClass` once and only do it on first get of the `validations` CP, we can just create the CPs on init which gives access to the container. I made the API a static function so we dont have to actually instantiate the validator to access the dependents. I was hoping to get feedback before I work on documentation.
Another thing I can add is
```bash
ember g validator --with-dependents
```
which will create a validator file with the static function override via `reopenClass`.
Ping …
=> Expose dependent keys api to validators

README.md
Needed to specify that this function comes out of the Ember object in the README example docs.
=> Add import for getOwner to README example

addon/validators/date.js, tests/unit/validators/date-test.js
The date validator is not working with format specified.
It always says invalid value.
It is first validated without the format, returns false, since Date() cannot parse it and then will return an error message and never tries with the format.
This fix skips the Date() check if format is specified
and fixes the data validator test to use a format that is not parsed by
Date()
=> Fix for data validator with format

addon/validations/factory.js, addon/validations/internal-result-object.js, addon/validations/result-collection.js, addon/validations/result.js, addon/validators/base.js, tests/integration/validations/factory-general-test.js
The options hash (`model.get('validations.attrs.username.options')`) is currently useless when a validator options is a function. This fixes that by having it contain the latest cached options. 
Resolves offirgolan/ember-bootstrap-cp-validations#4
=> Evaluate attrs options hash

addon/utils/utils.js, addon/validations/internal-result-object.js, addon/validators/ds-error.js, tests/index.html
=> [Bug Fix] Use Require for Checking Ember Data

addon/validations/factory.js
- Adds a check for null in `extractOptionsDependentKeys` (because `typeof null === "object"`)
=> Check for null in extractOptionsDependentKeys

tests/integration/validations/factory-general-test.js
- on `extractOptionsDependentKeys`: `typeof null === "object"`
Tasks:
=> Fix null value for the message

addon/validations/factory.js, addon/validations/result-collection.js, addon/validations/result.js, addon/validators/belongs-to.js, addon/validators/has-many.js, tests/unit/validations/nested-model-relationship-test.js
Resolves #283.
- Use RSVP.allSettled to make sure all promises will be resolved
- Implement readOnly property for Result class to determine if the InternalResultObject can be modified
Tasks:
=> [BUGFIX] Validate promise resolves even when validations are still validating

tests/dummy/app/components/validated-input.js
Resolves # .
In the component `validated-input`, the property `showErrorClass` was checking an undefined property (`showMessage`) which always makes it false and the component never got the `has-error` class, preventing the border of the input to turn red.
- Changed `showMessage` for `showErrorMessage` in [#L38](https://github.com/offirgolan/ember-cp-validations/blob/master/tests/dummy/app/components/validated-input.js#L38) of the component `validated-input`.
=> fixing input red borders in dummy app

addon/utils/utils.js, addon/validations/factory.js, addon/validations/internal-result-object.js, addon/validations/result-collection.js, addon/validations/result.js, addon/validations/validator.js, addon/validators/belongs-to.js, addon/validators/has-many.js, tests/dummy/app/models/user.js, tests/integration/validations/factory-general-test.js, tests/integration/validations/model-relationships-test.js, tests/unit/validators/dependent-test.js
Resolves #320.
- Lazily run validations if possible
- Exposes `lazy` common option which defaults to **true**
- Will only work with sync validations
Tasks:
=> [FEATURE] Lazily run validations

addon/validators/format.js, addon/validators/presence.js, tests/unit/validators/format-test.js
=> Add option allowNonTld for email format validator

addon/validations/factory.js, tests/integration/validations/factory-general-test.js
In the current implementation, we are using `defineProperty` to add CPs and nested object CPs in the `init` method of the attrs object creation. This is extremely slow and runs on a **per instance** basis. 
This PR removes the need for that by creating a tree of nested classes while applying the CPs on their protos. Once the attrs class is created, it instantiates those classes.
=> [BugFix] Define CPs and nested CPs in attrs object once per class

addon/utils/utils.js
We spoke about this on slack a week back, older versions of the loader do not support the `has` API.
=> Allow for requirejs.has to not be available

addon/validations/error.js, addon/validations/internal-result-object.js, addon/validations/result-collection.js, addon/validations/result.js, tests/integration/validations/factory-general-test.js
- Add validator type to error messages. It can be helpful if you're checking if there's a specific type of error in the collection.
Tasks:
```js
model.get('validations.errors').filterBy('type', 'unique-email');
// [ { type: 'presence',
//     message: 'This field can\'t be blank',
//     attribute: 'lastName' } ]
```
```js
model.get('validations.errors');
// [ { type: 'length',
//     message: 'This field is too short (minimum is 5 characters)',
//     attribute: 'firstName' },
//   { type: 'presence',
//     message: 'This field can\'t be blank',
//     attribute: 'lastName' } ]
```
```js
Validations = buildValidations({
firstName: [
validator('presence', true),
validator('length', {min: 5, max: 35})
],
lastName: [
validator('presence', true),
validator('length', {min: …
```
=> Add validator type to error messages

addon/utils/utils.js, package.json
```DEPRECATION: Ember.Handlebars.SafeString is deprecated in favor of Ember.String.htmlSafe [deprecation id: ember-htmlbars.ember-handlebars-safestring] See http://emberjs.com/deprecations/v2.x#toc_use-ember-string-htmlsafe-over-ember-handlebars-safestring for more details.```
- Add polyfill for `Ember.Handlebars.SafeString` to keep backwards compatibility.
Tasks:
- N/A
=> DEPRECATION: Ember.Handlebars.SafeString

addon/validations/factory.js
#Resolves regression in Ember 2.10.0-beta.*.
Currently lastObject is undefined and results in Ember.get(lastObject, ...) to throw with cannot get on undefined.
- Ember.get no longer will return the first argument when you pass an empty string as the key/path
- When you pass an empty string, return `this` like the original behavior
=> [BUGFIX] When the path is empty, use `this` for createAttrsClass

addon/-private/ember-validator.js, addon/validators/alias.js, addon/validators/belongs-to.js, addon/validators/collection.js, addon/validators/confirmation.js, addon/validators/date.js, addon/validators/dependent.js, addon/validators/ds-error.js, addon/validators/exclusion.js, addon/validators/format.js, addon/validators/has-many.js, addon/validators/inclusion.js, addon/validators/length.js, addon/validators/number.js, addon/validators/presence.js
Resolves #386  .
- Using the _type property on the validator to identify EV type was getting overridden by custom validators that were extending them. This fix uses a dedicated private property instead.
=> [BUGFIX] Resolve _type conflicts with EmberValidator classes

blueprints/ember-cp-validations/index.js, package.json
Update usage of `ember-cli-version-checker` to allow easier checking of Ember versions between `ember` bower package and `ember-source` npm package.
=> Add support for ember-source NPM package.

addon/validations/factory.js, tests/integration/validations/factory-general-test.js
- Create a static `resolveDebounce` method to pass run.debounce
Tasks:
=> [BUGFIX] Debounce context not properly set

addon/-private/internal-result-object.js, addon/-private/options.js, addon/-private/result.js, addon/utils/utils.js, addon/validations/factory.js, addon/validators/base.js, tests/integration/validations/factory-general-test.js
Resolves #381.
- Use `defineProperty` instead of creating classes via `Ember.Object.extend`
Finds:
- Initially when I ran the test case provided in #381 by @jakesjews, I got a resulting time of ~550ms. With the added changes, I now see around a 150ms to 200ms decrease in time (sometimes more).
- After a bunch of time debugging, it looks like using `extend` to create new classes take a lot longer than actually using `defineProperty` on init. 
cc @stefanpenner @rwjblue have you guys noticed this sort of thing in the past? I mean... it makes sense but from past experience, `defineProperty` is a pretty heavy hitter in terms of performance. 
Tasks:
=> [BUGFIX] Performance Improvements

addon/-private/factory-for.js, addon/validations/factory.js, addon/validators/base.js
No API surface has changed. `_factoryFor` will be removed in 2.13.
=> [BUGFIX] Replace private and deprecated `_lookupFactory` with public & performant `factoryFor`

addon/index.js
This addresses part of #193 by adding a note on container access to the "Basic" section of the docs. 
Hopefully this helps any developers (myself included) who might be prone to encounter the issue noted in #191 😄.
=> [DOCS] Add note on testing and container access to "Basic" documentation

addon/utils/utils.js, package.json
👋 -- We're updating [ember-string-ishtmlsafe-polyfill](https://github.com/workmanw/ember-string-ishtmlsafe-polyfill) to be a "native polyfill". Following the pattern provided by [ember-assign-polyfill](https://github.com/shipshapecode/ember-assign-polyfill) and [ember-getowner-polyfill](https://github.com/rwjblue/ember-getowner-polyfill).
Note: This is part of an effort to get all users of the polyfill updated.. workmanw/ember-string-ishtmlsafe-polyfill#5
=> Upgrading ember-string-ishtmlsafe-polyfill

addon/-private/ember-validator.js, addon/validators/format.js, addon/validators/length.js, package.json, tests/integration/validations/factory-general-test.js, tests/unit/validators/format-test.js
- Confirmation
- allowBlank
- Format
- inverse
- Length
- Default allowNone to true
- useBetweenMessage (If min and max are set, use the `between` error message type
- Number
- allowNone (defaulted to true)
- multipleOf
=> [FEATURE] Upgrade Ember Validators

addon/index.js
The example on Ember.Component had `user.lasName` validation field instead of correct `user.lastName`
Just documentation change
=> Documentation - Updated typo on example of validations

.travis.yml, config/ember-try.js
I'm not exactly sure what changed to make the test suite so unhappy, but in general ember-try seemed to be having problems installing ember data correctly so I updated a bunch of the failing scenarios to get them to work.
Of particular note:
* It might make sense to remove some of the older scenarios at some point
* I could not get the Ember 2.3 scenario working so I removed it.  Let me know if you feel strongly about keeping it and I can try again.
* The ember-release scenario was breaking because it couldn't run with ember data 2.14.  I think that is related to [this](https://github.com/emberjs/data/issues/5118) ember data issue so I made that scenario run with ember data 2.13 for now.
=> Attempt to fix the test suite

addon/-private/internal-result-object.js, addon/-private/result.js, addon/validations/factory.js, addon/validations/result-collection.js, addon/validators/dependent.js, tests/integration/validations/factory-general-test.js
Resolves #525 
- Adding isTruelyInvalid property
Tasks:
- [✔︎] Added test case(s)
- [✖️] Updated documentation
=> adding `isTruelyInvalid` property

addon/index.js, addon/utils/lookup-validator.js, addon/validations/factory.js, addon/validators/base.js, blueprints/validator-test/qunit-files/tests/unit/validators/__name__-test.js, package.json, tests/integration/validators/composable-test.js, yarn.lock
Easily compose complicated validations by using this `this.test` to validate
against pre-existing validators.
```javascript
validate(value, options, ...args) {
let result = this.test('presence', value, { presence: true }, ...args);
if (!result.isValid) {
return result.message;
}
result = this.test('number', value, { integer: true }, ...args);
// You can easily override the error message by returning your own.
if (!result.isValid) {
return 'This value must be an integer!';
}
// Add custom logic...
return true;
}
```
Tasks:
=> Validator Composability

addon/validations/factory.js
**partially** Resolves #485.
- Remove unnecessary closures
=> Partial memory leak fixes

addon/validations/factory.js, addon/validations/validator.js, addon/validators/base.js, addon/validators/inline.js, app/validators/inline.js, tests/dummy/app/models/signup.js, tests/integration/validations/factory-dependent-keys-test.js, tests/integration/validations/factory-general-test.js, tests/integration/validations/model-relationships-test.js, tests/unit/validations/ds-model-test.js, tests/unit/validators/inline-test.js
- Rework the inline validator to use the same layout as all other validators
Tasks:
=> Inline Validator

addon/validators/confirmation.js
- Fix minor copy-paste error on documentation.
Tasks:
=> Fix 'confirmation' example.

README.md, addon/-private/internal-result-object.js, addon/-private/result.js, addon/validations/factory.js, addon/validations/result-collection.js, tests/unit/validations/ds-model-test.js, tests/unit/validators/dependent-test.js
- Remove isDirty logic. This feature was never really complete and the `dirty` comparisons were very shallow. There are other libraries out there that people should use instead.
Tasks:
=> Remove isDirty

.eslintrc.js, .travis.yml, README.md, addon/decorators/has-validations.js, addon/index.js, package.json, tests/dummy/app/models/company.js, tests/unit/validations/ds-model-test.js, yarn.lock
Resolves #556 
- export a new function ```hasValidations``` class level decorator which allows you to add validations to an es6 style ember data model or component 
Tasks:
=> export hasValidations decorator for es6 style models

package.json, yarn.lock
This PR updates `ember-require-module` to get rid of Babel 5 deprecation warnings
Addresses https://github.com/offirgolan/ember-cp-validations/commit/92cbc833b6236e2339752d0e249f4c17be0b4b7d#commitcomment-28711518
/cc @offirgolan
=> Update `ember-require-module` to v0.1.3 (v3.x)

addon/validations/factory.js
Backport of #586 to the `v3.x` branch. I've opted to only backport the relevant change as the other things in #586 created a few complicated conflicts.
/cc @danielspaniel @offirgolan
=> Fix ObjectProxy extends validations bug (v3.x)

addon/index.js
Resolves no issue. Was wondering when the outdated ember-cli-babel will finally be upgraded until I noticed that the package name seems to has been changed.
- Updates the installation instructions to use @ember-intl/cp-validations instead of ember-intl-cp-validations
Tasks:
=> updated installation instructions for ember-intl support

package.json, yarn.lock
To address this:
> DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6
Looks like 4.x does not depend on this anymore, so only for 3.x
=> Bump ember-getowner-polyfill

addon/-private/result.js
Overwriting `_result` triggers a deprecation warning in newer versions of Ember.
This PR fixes this by instead writing another overwrite-property, which is used by _result instead (if set).
=> Do not override _result

blueprints/validator-test/index.js
Manually tested on our application using only ember-mocha and this
successfully generated the unit test.
- detect ember-mocha first, then ember-cli-mocha
@Turbo87 can correct me if I am wrong here, but I think applications using mocha for testing will only need to include `ember-mocha` going forward.
=> detect latest ember-mocha package as well

addon/validations/factory.js
Resolves #626 (but resolves it on the 3.x branch)
- This removes NAME_KEY  on the 3.x branch. See commit: https://github.com/offirgolan/ember-cp-validations/commit/283fc0596b2ee8a44eaa87704a56f135a69dd4ae
- This lets users use ember 3.12 and ember-cp-validations without using a beta.
Tasks:
[x] Ran tests--tests passed:
1..266
=> Remove NAME_KEY from addon/validations/factory.js

.travis.yml, blueprints/validator-test/index.js, package.json, yarn.lock
v6 was end of life in April 2019 and is no longer supported.
This is required for #662
=> [Breaking] Drop Node 6

addon/utils/get-with-default.js, addon/validations/factory.js, addon/validators/dependent.js, tests/unit/utils/get-with-default-test.js
Resolves #680.
This PR aims to remove all usage of `getWithDefault` function into `ember-cp-validations`
Here's the link of the deprecation https://deprecations.emberjs.com/v3.x/#toc_ember-metal-get-with-default
Heavily inspired by [getWithDefautl function in Ember](https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/metal/lib/property_get.ts#L180)
- update to replace `getWithDefault` with `get` in `addon/validators/dependent.js`
- update to replace `getWithDefault` with `get` in `addon/validations/factory.js`
I wanted to use the **Nullish coalescing operator** `??` but it's not available yet in this repo .. :/
=> Replace `getWithDefault` function 

.travis.yml, package.json, yarn.lock
Part of #680 
`getWithDefault` has been replaced in dependency `ember-validators`: offirgolan/ember-validators/pull/77
So I had to bump the project node version also 🤔 
Let me know if I should pluck the node update into a separate PR
=> Bump node version and ember-validators from ^2.0.0 to ^3.0.1

CHANGELOG.md, package.json, tests/dummy/app/models/user-detail.js, tests/unit/validators/date-test.js, yarn.lock
Resolves # 
- To get the updated version of `ember-cli-babel` which is causing depreciation warnings
- Updating `ember-validators` as it's current version is already having updated babel version
Tasks:
=> Updated ember required and ember validators packages

addon/validations/factory.js
Ember 4.0 removed `.volatile()` on `computed()`. This PR adds the deprecation to remove it in version `5.0` of this addon.
Tests for ember-4.0, release, beta, and canary are expected to fail.
=> Deprecate volatile option

README.md
@MelSumner can you remove the required Travis CI check:
=> Replace travis with github actions badge

addon/utils/utils.js, package.json, yarn.lock
In order to place nicely with Embroider, we need to remove `require`. Instead we can use `dependencySatisfies` and `importSync`.
Resolves #740
- Remove `require` and replace with `dependencySatisfies` and `importSync`. ([docs](https://github.com/embroider-build/embroider/tree/main/packages/macros#dependencysatisfies))
Tasks:
N/A
=> Replace require with @embroider/macros

.github/workflows/ci.yml, package.json, yarn.lock
I didn't include this in https://github.com/adopted-ember-addons/ember-cp-validations/pull/742 because by default ember-data isn't part of the addon blueprint 👍
=> bump default ember-data version

addon/index.js, addon/utils/deep-set.js, addon/validations/factory.js, addon/validators/base.js, addon/validators/belongs-to.js, addon/validators/has-many.js
This is a cherry-pick of work done by @fsmanuel in https://github.com/adopted-ember-addons/ember-cp-validations/pull/736
I'm just extracting the changes because they are individually important and not related to updating any more 👍
=> Remove Ember. from doc strings

addon/utils/utils.js
This is a cherry-pick of work done by @fsmanuel in https://github.com/adopted-ember-addons/ember-cp-validations/pull/736
I'm just extracting the changes because they are individually important and not related to updating any more 👍
=> Don’t use isArray on ember data objects

package.json
I'm not exactly sure what happened 🤔 but in merging some of the recent PRs we ended up with 2 `peerDependencies` blocks 🤷 this PR fixes that 👍
=> fix peer-dependencies

.github/workflows/ci.yml, addon/-private/options.js, package.json, pnpm-lock.yaml
The `@embroider/test-setup` package was very out of date so we really couldn't expect the `embroider-safe` or `embroider-optimised` tests to pass without updating it 👍
=> update @embroider/test-setup to fix CI
